### ISSUE TITLE
Podcast cannot be saved in admin interface

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/mygpo#316]
When editing a podcast in the admin interface (`/admin/`), saving often fails because some fields are treated as mandatory, even though they should be optional. This includes

* License (can be empty if no license is known)
* Flattr url (can be empty if flattr is not used)
* Group (can be empty if podcast is not part of a group)
* Group member name (can be empty if podcast is not part of a group)
* New location (only non-empty if pocdast is redirected)

Most likely this is caused by incorrect usage of the `blank` and `null` attributes of the respective model fields.

See https://docs.djangoproject.com/en/3.0/ref/models/fields/#field-options and https://docs.djangoproject.com/en/dev/ref/contrib/admin/ for further information.

If the issue is fixed with correcting the blank and null attributes, a corresponding migration is needed which can be created with `manage.py makemigrations`.

**Comment by fundatillus** [comment]
I've got this.

**Comment by stefankoegl** [comment]
Fixed by #317.

**Comment by fundatillus** [comment]
Still have issues. When tags aren't formatted as slugs (alphanumeric and underscores only) and/or a user is not specified, still unable to save from admin interface.
